openapi: 3.0.1
info:
  title: Todo Service API
  description: This is an api-spec for `todo` service.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mothusi Molorane
    email: molorane.mothusi@gmail.com
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 0.0.1
servers:
  - url: http://localhost:2023/todo
    description: Generated server url
tags:
  - name: Todo
    description: Api operations for the todo
paths:
  /v1/task/{userId}:
    get:
      tags:
        - Todo
      summary: Find todos by accountId
      description: Find todos by accountId
      operationId: findAllByAccountId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoDTO'
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - Todo
      summary: Add a todo
      description: Add a todo
      operationId: addTodo
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoDTO'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoDTO'
        '204':
          description: No Content
        '400':
          description: Invalid ID supplied
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TodoDTO'
        '404':
          description: Todo not found
          content:
            '*/*':
              schema:
                type: string
        '405':
          description: Validation exception
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TodoDTO'
components:
  schemas:
    TodoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        todoType:
          type: string
          enum:
            - PRAYER
            - GYM
            - EVANGELISM
            - FLUTTER
            - SPRING
            - STUDY
            - FOOD
            - ENTERTAINMENT
        title:
          type: string
        completed:
          type: boolean
        dueDate:
          type: string
          format: date
        description:
          type: string
        createdDate:
          type: string
          format: date-time
        deleted:
          type: boolean
