server:
  port: 2023
  servlet:
    context-path: /todo

app:
  version: 0.0.1
  description: "This is an api-spec for `todo` service."
  developer:
    email: molorane.mothusi@gmail.com
    name: Mothusi Molorane

spring:
  application:
    name: todo

---
---
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    username: root
    password: blessing
    url: jdbc:mysql://localhost:3306/todos?serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true